insert into countries values (1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 036,'Australia');
insert into countries values (2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 040, 'Austria');
insert into countries values (3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 044, 'Bahamas');
insert into countries values (4, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 204, 'Benin');
insert into countries values (5, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 076, 'Brazil');
insert into countries values (6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 398, 'Kazakhstan');
insert into countries values (7, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 136, 'Cayman islands');
insert into countries values (8, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 124, 'Canada');
insert into countries values (9, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 428, 'Latvia');
insert into countries values (10, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 528, 'Netherlands');
insert into countries values (11, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 604, 'Peru');
insert into countries values (12, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 052, 'Barbados');
insert into countries values (13, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 112, 'Belarus');
insert into countries values (14, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 276, 'Germany');
insert into countries values (15, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 818, 'Egypt');
insert into countries values (16, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 458, 'Malaysia');
insert into countries values (17, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 524, 'Nepal');
insert into countries values (18, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 688, 'Serbia');
insert into countries values (19, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 792, 'Turkey');
insert into countries values (20, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 392, 'Japan');
insert into countries values (21, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 218, 'Ecuador');

insert into population values (1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), false, 18, 'German', 'Martin', '2745469', 'M');
insert into population values (2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), false, 12, 'Danya', 'Jordan', '1397820', 'M');
insert into population values (3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), false, 25, 'Iegor', 'Jackson', '9667709', 'M');
insert into population values (4, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), false, 3, 'Oleg', 'Grant', '4254032', 'M');
insert into population values (5, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), false, 11, 'John', 'Evans', '4278724', 'M');
insert into population values (6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), false, 56, 'Lesha', 'Stone', '5488066', 'M');
insert into population values (7, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), false, 90, 'Gleb', 'Roberts', '7964513', 'M');
insert into population values (8, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), false, 21, 'Vika', 'Mills', '7972851', 'F');
insert into population values (9, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), false, 29, 'Dasha', 'Lewis', '9945992', 'F');
insert into population values (10, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), false, 34, 'Viktoria', 'Morgan', '7499091', 'F');
insert into population values (11, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), false, 67, 'Petya', 'Florence', '7885543', 'M');
insert into population values (12, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), false, 78, 'Andrei', 'Campbell', '5906290', 'M');
insert into population values (13, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), false, 82, 'Cristobal', 'Bronte', '5029690', 'F');
insert into population values (14, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), false, 5, 'Fabio', 'Bell', '7223194', 'M');
insert into population values (15, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), false, 10, 'Gijs', 'Adams', '7566521', 'M');
insert into population values (16, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), false, 55, 'Johannes', 'Williams', '8814096', 'F');
insert into population values (17, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), false, 39, 'Frankie', 'Peters', '8849725', 'M');
insert into population values (18, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), false, 88, 'Belle', 'Davis', '5177628', 'F');
insert into population values (19, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), false, 23, 'Greta', 'Collins', '6720862', 'F');
insert into population values (20, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), false, 51, 'Hazel', 'Bradley', '1652303', 'F');
insert into population values (21, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), false, 18, 'Edith', 'Barlow', '8492669', 'M');
insert into population values (22, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), false, 54, 'Gorge', 'Brown', '6499969', 'M');
