insert into users values (1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 18,'Kiev','email1@gmail.com', 'German', 'Martin', '2745469');
insert into users values (2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 12,'Kharkov','email2@gmail.com', 'Danya', 'Jordan', '1397820');
insert into users values (3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 25,'Odessa','email3@gmail.com', 'Iegor', 'Jackson', '9667709');
insert into users values (4, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 3,'Dnieper','email4@gmail.com', 'Oleg', 'Grant', '4254032');
insert into users values (5, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 11,'Donetsk','email5@gmail.com', 'John', 'Evans', '4278724');
insert into users values (6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 56,'Zaporizhzhia','email6@gmail.com', 'Lesha', 'Stone', '5488066');
insert into users values (7, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 90,'Lviv','email7@gmail.com', 'Gleb', 'Roberts', '7964513');
insert into users values (8, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 21,'Sevastopol','email8@gmail.com', 'Vika', 'Mills', '7972851');
insert into users values (9, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 29,'Nikolaev','email9@gmail.com', 'Dasha', 'Lewis', '9945992');
insert into users values (10, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 34,'Mariupol','email10@gmail.com', 'Viktoria', 'Morgan', '7499091');
insert into users values (11, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 67,'Luhansk','email11@gmail.com', 'Petya', 'Florence', '7885543');
insert into users values (12, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 78,'Vinnytsia','email12@gmail.com', 'Andrei', 'Campbell', '5906290');
insert into users values (13, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 82,'Makeevka','email13@gmail.com', 'Cristobal', 'Bronte', '5029690');
insert into users values (14, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 5,'Simferopol','email14@gmail.com', 'Fabio', 'Bell', '7223194');
insert into users values (15, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 10,'Kherson','email15@gmail.com', 'Gijs', 'Adams', '7566521');
insert into users values (16, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 55,'Chernihiv','email16@gmail.com', 'Johannes', 'Williams', '8814096');
insert into users values (17, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 39,'Poltava','email17@gmail.com', 'Frankie', 'Peters', '8849725');
insert into users values (18, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 88,'Khmelnitsky','email18@gmail.com', 'Belle', 'Davis', '5177628');
insert into users values (19, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 23,'Cherkasy','email19@gmail.com', 'Greta', 'Collins', '6720862');
insert into users values (20, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 51,'Chernivtsi','email20@gmail.com', 'Hazel', 'Bradley', '1652303');
insert into users values (21, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 18,'Zhytomyr','email21@gmail.com', 'Edith', 'Barlow', '8492669');
insert into users values (22, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 54,'Sumy','email22@gmail.com', 'Gorge', 'Brown', '6499969');

insert into categories values (1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, true, 'Получил на новый год');
insert into categories values (2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, false, 'Сходил в магазин');
insert into categories values (3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, true, 'Пришла зарплата');
insert into categories values (4, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, false, 'Потерял');
insert into categories values (5, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, true, 'Выиграл в лотерею');
insert into categories values (6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, false, 'Отплатил коммуналку');
insert into categories values (7, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, true, 'Отдал бездомному');
insert into categories values (8, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, false, 'Погулял с девушкой');
insert into categories values (9, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, true, 'Продал какую-то вещь');
insert into categories values (10, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, false, 'Купил какую-то вещь');