insert into countries values (1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Australia', 036);
insert into countries values (2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Austria', 040);
insert into countries values (3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Bahamas', 044);
insert into countries values (4, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Benin', 204);
insert into countries values (5, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Brazil', 	076);
insert into countries values (6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Kazakhstan', 398);
insert into countries values (7, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Cayman islands', 136);
insert into countries values (8, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Canada', 124);
insert into countries values (9, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Latvia', 428);
insert into countries values (10, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Netherlands', 528);
insert into countries values (11, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Peru', 604);
insert into countries values (12, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Barbados', 052);
insert into countries values (13, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Belarus', 112);
insert into countries values (14, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Germany', 276);
insert into countries values (15, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Egypt', 818);
insert into countries values (16, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Malaysia', 458);
insert into countries values (17, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Nepal', 524);
insert into countries values (18, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Serbia', 688);
insert into countries values (19, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Turkey', 792);
insert into countries values (20, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Japan', 392);
insert into countries values (20, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Ecuador', 218);

insert into population values (1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'German', 'Martin', 18, 'M', '2745469');
insert into population values (2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Danya', 'Jordan', 12, 'M', '1397820');
insert into population values (3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Iegor', 'Jackson', 25, 'M', '9667709');
insert into population values (4, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Oleg', 'Grant', 3, 'M', '4254032');
insert into population values (5, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'John', 'Evans', 11, 'M', '4278724');
insert into population values (6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Lesha', 'Stone', 56, 'M', '5488066');
insert into population values (7, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Gleb', 'Roberts', 90, 'M', '7964513');
insert into population values (8, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Vika', 'Mills', 21, 'F', '7972851');
insert into population values (9, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Dasha', 'Lewis', 29, 'F', '9945992');
insert into population values (10, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Viktoria', 'Morgan', 34, 'F', '7499091');
insert into population values (11, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Petya', 'Florence', 67, 'M', '7885543');
insert into population values (12, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Andrei', 'Campbell', 78, 'M', '5906290');
insert into population values (13, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Cristobal', 'Bronte', 82, 'F', '5029690');
insert into population values (14, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Fabio', 'Bell', 5, 'M', '7223194');
insert into population values (15, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Gijs', 'Adams', 10, 'M', '7566521');
insert into population values (16, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Johannes', 'Williams', 55, 'F', '8814096');
insert into population values (17, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Frankie', 'Peters', 39, 'M', '8849725');
insert into population values (18, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Belle', 'Davis', 88, 'F', '5177628');
insert into population values (19, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Greta', 'Collins', 23, 'F', '6720862');
insert into population values (20, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Hazel', 'Bradley', 51, 'F', '1652303');
insert into population values (21, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Edith', 'Barlow', 18, 'M', '8492669');
insert into population values (22, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), false, 'Gorge', 'Brown', 54, 'M', '6499969');

insert into country_person values (1, 1);
insert into country_person values (2, 1);
insert into country_person values (2, 12);
insert into country_person values (3, 3);
insert into country_person values (1, 2);
insert into country_person values (4, 4);
insert into country_person values (4, 5);
insert into country_person values (4, 6);
insert into country_person values (5, 6);
insert into country_person values (6, 7);
insert into country_person values (7, 7);
insert into country_person values (7, 8);
insert into country_person values (7, 14);
insert into country_person values (7, 9);
insert into country_person values (8, 9);
insert into country_person values (9, null);
insert into country_person values (10, 10);
insert into country_person values (11, 11);
insert into country_person values (12, 1);
insert into country_person values (12, 6);
insert into country_person values (13, 6);
insert into country_person values (13, 15);
insert into country_person values (14, 19);
insert into country_person values (14, 20);
insert into country_person values (14, 11);
insert into country_person values (14, 18);
insert into country_person values (15, 1);
insert into country_person values (15, 2);
insert into country_person values (16, 20);
insert into country_person values (16, 19);
insert into country_person values (16, 13);
insert into country_person values (17, 13);
insert into country_person values (17, 8);
insert into country_person values (18, null);
insert into country_person values (19, 6);
insert into country_person values (19, 8);
insert into country_person values (19, 5);
insert into country_person values (19, 10);
insert into country_person values (19, 17);
insert into country_person values (20, 16);
insert into country_person values (20, 21);
insert into country_person values (21, 21);